### ISSUE TITLE
attempting to require primus-multiplex

### ISSUE THREAD

**Issue by blackbumer** [cayasso/primus.io#17]
module.js:340
    throw err;
          ^
Error: Cannot find module 'primus-multiplex'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at PrimusIO.use (/Users/danil/Developer/test_socket_bga/pingpong/node_modules/primus/index.js:677:15)
    at new PrimusIO (/Users/danil/Developer/test_socket_bga/pingpong/node_modules/primus.io/lib/index.js:33:4)
    at Object.<anonymous> (/Users/danil/Developer/test_socket_bga/pingpong/app.js:27:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Process finished with exit code 8

my package.json:
{
  "name": "pingpong",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^2.4.1",
    "primus": "^2.4.12",
    "primus.io": "^3.1.2",
    "ws": "^0.7.0"
  }
}

**Comment by cayasso** [comment]
Hey @blackbumer if this is still an issue for you feel free to reopen but
`primus-multiplex` is already included as dependency in this library, you can confirm by checking your node_modules folder https://github.com/cayasso/primus.io/blob/master/package.json#L36
